version: '3.9'
services:
#  api:
#    build: .
#    container_name: node_api
#    ports:
#      - "3000:3000"
#    command: npm run dev
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
#    depends_on:
#      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./setup-database:/docker-entrypoint-initdb.d

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db

volumes:
  pgdata:
